import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

import localFont from "@next/font/local";

export const metadata = {
  title: "Coffee App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav className=" bottom" />
        <div>{children}</div>
      </body>
    </html>
  );
}
